version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mercylab
      POSTGRES_USER: mercylab
      POSTGRES_PASSWORD: mercylabpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mercylab -d mercylab"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      PORT: 4000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: mercylab
      DB_USER: mercylab
      DB_PASS: mercylabpass
      JWT_SECRET: change_this_secret_to_something_long_and_random
      JWT_EXPIRES_IN: 7d
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/usr/src/app
    command: ["npm", "run", "start"]

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata:
